services:
  api_token_pool:
    build:
      context: .
      target: dev
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    container_name: api_token_pool
    command: mix phx.server
    depends_on:
      api_token_pool_db:
        condition: service_healthy
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - api_token_pool_deps:/app/deps
      - api_token_pool_build:/app/_build
    env_file:
      - .env
    networks:
      - api_token_pool_net

  api_token_pool_db:
    image: "postgres:17"
    container_name: api_token_pool_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "api_token_pool_db:/var/lib/postgresql/data"
    networks:
      - api_token_pool_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  api_token_pool_db:
  api_token_pool_deps:
  api_token_pool_build:

networks:
  api_token_pool_net:
